import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.jsx'

// Registers the service worker generated by vite-plugin-pwa so the app shell
// (and any previously-loaded images/videos, see vite.config.js) keeps working
// without a network connection. AI-backed features still need connectivity.
registerSW({ immediate: true })

createRoot(document.getElementById('root')).render(<App />)
